apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: marain-tenancy-service
  description: API to support Tenancy in Marain.
  annotations:
    github.com/project-slug: 'marain-dotnet/marain.tenancy'
    backstage.io/adr-location: 'https://github.com/marain-dotnet/Marain.Tenancy/tree/main/docs/adr'
    endjin.com/imm-location: https://github.com/marain-dotnet/Marain.Tenancy/blob/main/imm.yaml
    dev.azure.com/project: Marain.Tenancy
    dev.azure.com/build-definition: CI
    endjin.com/sbom-repo-name: Marain.Tenancy
  links: []
spec:
  type: service
  lifecycle: production
  owner: endjineers
  system: marain
  dependsOn:
  - component:corvus-testing
  providesApis:
  - marain-tenancy-api