apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: marain-workflow-service
  description: API to support Workflow in Marain.
  annotations:
    github.com/project-slug: 'marain-dotnet/marain.workflow'
    backstage.io/adr-location: 'https://github.com/marain-dotnet/Marain.Workflow/tree/master/docs/adr'
  links: []
spec:
  type: service
  lifecycle: production
  owner: endjineers
  system: marain
  dependsOn:
  - component:corvus-testing
  - api:marain-tenancy-api
  - api:marain-operations-control-api
  - api:marain-operations-status-api
  providesApis:
  - marain-workflow-engine-api