apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: marain-workflow
  description: API to support Workflow in Marain.
  annotations:
    github.com/project-slug: 'marain-dotnet/marain.workflow'
  links: []
spec:
  type: service
  lifecycle: production
  owner: endjin
  system: marain
  dependsOn:
  - component:corvus-testing
  - api:marain-tenancy
  - api:marain-operations-control
  - api:marain-operations-status
  providesApis:
  - marain-workflow-api